
/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  type UnencryptedL2Log,
  type Wallet,
  type WrappedFieldLike,
} from '@aztec/aztec.js';
import ZImburseRegistryContractArtifactJson from './ZImburseRegistry.json' assert { type: 'json' };
// @ts-ignore
export const ZImburseRegistryContractArtifact = loadContractArtifact(ZImburseRegistryContractArtifactJson as NoirCompiledContract);


export type DKIMKeyHashRegistered = {
  dkim_key_hash: FieldLike
  verifier_id: FieldLike
}


/**
 * Type-safe interface for contract ZImburseRegistry;
 */
export class ZImburseRegistryContract extends ContractBase {

  private constructor(
    instance: ContractInstanceWithAddress,
    wallet: Wallet,
  ) {
    super(instance, ZImburseRegistryContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    return Contract.at(address, ZImburseRegistryContract.artifact, wallet) as Promise<ZImburseRegistryContract>;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, usdc: AztecAddressLike, escrow_contract_id: FieldLike, verifier_ids: FieldLike[], dkim_key_hashes: FieldLike[]) {
    return new DeployMethod<ZImburseRegistryContract>(Fr.ZERO, wallet, ZImburseRegistryContractArtifact, ZImburseRegistryContract.at, Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeysHash(publicKeysHash: Fr, wallet: Wallet, usdc: AztecAddressLike, escrow_contract_id: FieldLike, verifier_ids: FieldLike[], dkim_key_hashes: FieldLike[]) {
    return new DeployMethod<ZImburseRegistryContract>(publicKeysHash, wallet, ZImburseRegistryContractArtifact, ZImburseRegistryContract.at, Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof ZImburseRegistryContract['methods']>(
    opts: { publicKeysHash?: Fr; method?: M; wallet: Wallet },
    ...args: Parameters<ZImburseRegistryContract['methods'][M]>
  ) {
    return new DeployMethod<ZImburseRegistryContract>(
      opts.publicKeysHash ?? Fr.ZERO,
      opts.wallet,
      ZImburseRegistryContractArtifact,
      ZImburseRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return ZImburseRegistryContractArtifact;
  }


  public static get storage(): ContractStorageLayout<'definition' | 'escrow_registry' | 'dkim_registry' | 'managed_escrows' | 'participants' | 'participant_escrows'> {
    return {
      definition: {
        slot: new Fr(1n),
      },
      escrow_registry: {
        slot: new Fr(4n),
      },
      dkim_registry: {
        slot: new Fr(5n),
      },
      managed_escrows: {
        slot: new Fr(6n),
      },
      participants: {
        slot: new Fr(7n),
      },
      participant_escrows: {
        slot: new Fr(8n),
      }
    } as ContractStorageLayout<'definition' | 'escrow_registry' | 'dkim_registry' | 'managed_escrows' | 'participants' | 'participant_escrows'>;
  }


  public static get notes(): ContractNotes<'AddressNote' | 'TransparentNote' | 'TokenNote' | 'RecurringEntitlementNote' | 'ParticipantNote'> {
    return {
      AddressNote: {
        id: new NoteSelector(2232136525),
      },
      TransparentNote: {
        id: new NoteSelector(3193649735),
      },
      TokenNote: {
        id: new NoteSelector(2350566847),
      },
      RecurringEntitlementNote: {
        id: new NoteSelector(3639716131),
      },
      ParticipantNote: {
        id: new NoteSelector(3017618054),
      }
    } as ContractNotes<'AddressNote' | 'TransparentNote' | 'TokenNote' | 'RecurringEntitlementNote' | 'ParticipantNote'>;
  }


  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** check_and_register_participant(participant: struct, participant_name: string, escrow: struct) */
    check_and_register_participant: ((participant: AztecAddressLike, participant_name: string, escrow: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** check_dkim_key_hash_private(dkim_key_hash: field) */
    check_dkim_key_hash_private: ((dkim_key_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** check_dkim_key_hash_public(dkim_key_hash: field) */
    check_dkim_key_hash_public: ((dkim_key_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, serialized_note: array) */
    compute_note_hash_and_optionally_a_nullifier: ((contract_address: AztecAddressLike, nonce: FieldLike, storage_slot: FieldLike, note_type_id: FieldLike, compute_nullifier: boolean, serialized_note: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** constructor(usdc: struct, escrow_contract_id: field, verifier_ids: array, dkim_key_hashes: array) */
    constructor: ((usdc: AztecAddressLike, escrow_contract_id: FieldLike, verifier_ids: FieldLike[], dkim_key_hashes: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_escrow_class_id() */
    get_escrow_class_id: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_escrow_registry_status(escrow_contract: struct) */
    get_escrow_registry_status: ((escrow_contract: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_managed_escrows(offset: integer) */
    get_managed_escrows: ((offset: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participant_escrows(participant: struct, offset: integer) */
    get_participant_escrows: ((participant: AztecAddressLike, offset: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_participants(escrow: struct, offset: integer) */
    get_participants: ((escrow: AztecAddressLike, offset: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_dkim(verifier_id: field, dkim_key_hash: field) */
    register_dkim: ((verifier_id: FieldLike, dkim_key_hash: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_dkim_bulk(verifier_ids: array, dkim_key_hashes: array) */
    register_dkim_bulk: ((verifier_ids: FieldLike[], dkim_key_hashes: FieldLike[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_escrow(escrow_contract: struct) */
    register_escrow: ((escrow_contract: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** register_participant(participant: struct, participant_name: string, admin: struct, escrow: struct) */
    register_participant: ((participant: AztecAddressLike, participant_name: string, admin: AztecAddressLike, escrow: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


  // Partial application is chosen is to avoid the duplication of so much codegen.
  private static decodeEvent<T>(
    eventSelector: EventSelector,
    eventType: AbiType,
  ): (payload: L1EventPayload | UnencryptedL2Log | undefined) => T | undefined {
    return (payload: L1EventPayload | UnencryptedL2Log | undefined): T | undefined => {
      if (payload === undefined) {
        return undefined;
      }

      if (payload instanceof L1EventPayload) {
        if (!eventSelector.equals(payload.eventTypeId)) {
          return undefined;
        }
        return decodeFromAbi([eventType], payload.event.items) as T;
      } else {
        let items = [];
        for (let i = 0; i < payload.data.length; i += 32) {
          items.push(new Fr(payload.data.subarray(i, i + 32)));
        }

        return decodeFromAbi([eventType], items) as T;
      }
    };
  }

  public static get events(): { DKIMKeyHashRegistered: { decode: (payload: L1EventPayload | UnencryptedL2Log | undefined) => DKIMKeyHashRegistered | undefined, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      DKIMKeyHashRegistered: {
        decode: this.decodeEvent(EventSelector.fromSignature('DKIMKeyHashRegistered(Field,Field)'), {
          "fields": [
            {
              "name": "dkim_key_hash",
              "type": {
                "kind": "field"
              }
            },
            {
              "name": "verifier_id",
              "type": {
                "kind": "field"
              }
            }
          ],
          "kind": "struct",
          "path": "ZImburseRegistry::DKIMKeyHashRegistered"
        }),
        eventSelector: EventSelector.fromSignature('DKIMKeyHashRegistered(Field,Field)'),
        fieldNames: ["dkim_key_hash", "verifier_id"],
      }
    };
  }

}
